### ISSUE TITLE
PDF of v3 Schematics / Layout

### ISSUE THREAD

**Issue by josschne** [Protocentral/ProtoCentral_ads1262#6]
Could we get a PDF of the v3 hardware schematics and layout for those without Eagle?

I see the v3 design files but no PDF.
https://github.com/Protocentral/ADS1292rShield_Breakout/tree/master/Hardware/ECG_BOB

**Comment by VenkateshBhat** [comment]
Thank you for bringing this to our attention, now we have added the pdf file for the breakout https://github.com/Protocentral/ADS1292rShield_Breakout/tree/master/Hardware/ECG_BOB

**Comment by josschne** [comment]
Thanks for the fast response. However, the PDF is missing the second sheet.

Could I see the second sheet too? The v3 hardware has logic level selection circuitry that I'd like to examine.

**Comment by VenkateshBhat** [comment]
added, do check.

**Comment by josschne** [comment]
Thanks!
